### ISSUE TITLE
Public TA Schedules?

### ISSUE THREAD

**Issue by jamiecounsell** [PhilGabardo/Schedule-Maker#1]
The TA's schedules should certainly not be checked in to any version control. My schedule and personal email address should not be on public domain. It doesn't matter now for this information, but keep this in mind in the future.

**Comment by PhilGabardo** [comment]
Thanks, didn't consider this when checking in the project. I've deleted all files containing TA names.

**Comment by jamiecounsell** [comment]
a483bdee7fbec78e9977b59ddcb18c8348aa407b thanks!
